### ISSUE TITLE
Table styling fixes

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/gatsby-theme-patternfly-org#106]
We need to refine our approach to tables across the site. We had 3 different table styles, and now we have 2, but the bottom image does not quite work for our documentation and we'll need to decide what our approach should be. I think if we can play with the alignment that would be ideal.

<img width="896" alt="Screen Shot 2019-11-08 at 9 06 19 AM" src="https://user-images.githubusercontent.com/40275806/68482379-76d63d80-0207-11ea-986d-baff30c49c1b.png">

<img width="1277" alt="Screen Shot 2019-11-08 at 9 13 25 AM" src="https://user-images.githubusercontent.com/40275806/68482706-21e6f700-0208-11ea-8772-515b96d10b41.png">

<img width="926" alt="Screen Shot 2019-11-08 at 9 05 58 AM" src="https://user-images.githubusercontent.com/40275806/68482773-4511a680-0208-11ea-9c35-149340977c5e.png">

Notice these two tables have different responsive behaviors:

<img width="679" alt="Screen Shot 2019-11-08 at 9 15 26 AM" src="https://user-images.githubusercontent.com/40275806/68483624-e8af8680-0209-11ea-88df-b8ad900b5ff7.png">

**Comment by redallen** [comment]
It'd be difficult to change the Core table to a more dynamic React table like the "CSS Variables" table or like the "AlertActionCloseButton" table.

It'd be easier to change the "CSS Variables" and "AlertActionClose" button tables. How do we want those to be rendered, and how should the breakpoints work? Should columns squish like Core/React tables, or expand like the "CSS Variables" table?
