### ISSUE TITLE
Issues in Staging for release

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/gatsby-theme-patternfly-org#128]
Browser: Chrome
left nav disappears when clicking on RH font:
<img width="1358" alt="Screen Shot 2019-11-25 at 1 06 15 PM" src="https://user-images.githubusercontent.com/40275806/69566180-8209c700-0f84-11ea-9609-750a1f7010f4.png">

As seen on the wireframes we need a header for Release Notes to match the other pages:

<img width="1207" alt="Screen Shot 2019-11-25 at 1 08 36 PM" src="https://user-images.githubusercontent.com/40275806/69566307-c8f7bc80-0f84-11ea-8003-42e9b084902d.png">

**Comment by rachael-phillips** [comment]
The feature on the context selector where you can switch between features like Spinner and Spinner is not working

**Comment by redallen** [comment]
@rachael-phillips The maintaining context while switching is working, but only works for components with design documentation.

I'll add an empty file for Spinner.
