### ISSUE TITLE
Design changes to make to the site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/gatsby-theme-patternfly-org#20]
**All site pages**
- Fix the grey backgrounds - we need all of the background colors to match current site
- [x] Add the PF3 banner back in
- [x] Add footer back in. Footer should live on every page.

~~**Masthead**~~
- [x] Functionality and animation of the navigation. The patternfly.org/v4 masthead has custom styling and animation. 
- [x] Add logo to masthead
- [x] Add custom styling to masthead
- [x] Add global search and custom search styling

~~**Left nav**~~
- [x] Add custom styling and behavior that you see on patternfly.org/v4

~~**Homepage**~~
- All styling for homepage
    - [x] The buttons need styling
    - [x] Add Images
    - [x] Links need to be fixed
    - [x] Add background images

**All get started pages**
- Fix broken internal links
- Remove table of contents and (Get-started) tag
- Add padding
- Remove random Props header

**Design guidelines**

All design guidelines pages
- Fix broken internal links
- Remove table of contents
- Add padding to design guidelines pages
- Remove random Props header

~~Colors~~
- [x] Add color images back into page

~~Icons~~
- [x] Merge Evan’s PR for Icons page and add copy to clipboard feature

~~Spacers~~
- [x] Add spacers back images back in

~~Typography~~
- [x] Typography page is missing and needs to be added back in.
- [x] Evan and/or Zack will demo to Rachael for awareness

**Documentation pages**

All documentation pages
- [x] Add Padding
- Add Styling of copied to clipboard to the copy to clipboard feature - font needs to be fixed
- [x] Add Styling of code examples - it needs to match patternfly.org/v4 and the font size needs to be bigger to match patternfly.org/v4

All HTMLpages
- Handlebars icon should remain on site
- Remove random Props headers that are appearing on HTML pages currently
- Make sure example images appear on Brand Component page and About Modal example. Right now they do not.

Experimental pages
- Add the experimental in-line alert back to experimental pages.
    - "Divider" frontmatter needs to be updated in React

~~Opt-in pages~~
- [x] Make sure in-line alert is on each opt-in page.

Get in touch
- [x] **Add Get in touch page**
- should go over design with Rachael

**Comment by rachael-phillips** [comment]
Masthead

- The text on the masthead should be light grey rather than white
<img width="1401" alt="Screen Shot 2019-10-30 at 3 31 02 PM" src="https://user-images.githubusercontent.com/40275806/67892102-5f71c300-fb2a-11e9-989a-7cb2783742cb.png">

I know it may look whit but it's actually light grey.

Homepage

- [ ]  First top Background images need to be updates to be accurate to current homepage. 
<img width="1608" alt="Screen Shot 2019-10-30 at 3 19 28 PM" src="https://user-images.githubusercontent.com/40275806/67891296-b080b780-fb28-11e9-9763-edf0167cd66e.png">

- [ ] Button styling
- [ ] Fix padding on homepage
- [ ] The text below needs to be aligned
<img width="716" alt="Screen Shot 2019-10-30 at 3 20 27 PM" src="https://user-images.githubusercontent.com/40275806/67891391-defe9280-fb28-11e9-8d24-f401f1bf7ed1.png">

The text should also be aligned with text in the footer
<img width="235" alt="Screen Shot 2019-10-30 at 3 22 18 PM" src="https://user-images.githubusercontent.com/40275806/67891534-1ff6a700-fb29-11e9-81c5-074e55ca20b8.png">


All pages
- [ ] Headers have disappeared and should be updated

Bug in footer
- [ ]  Blue underline in footer
<img width="204" alt="Screen Shot 2019-10-30 at 3 24 36 PM" src="https://user-images.githubusercontent.com/40275806/67891679-6e0baa80-fb29-11e9-9703-9b975953043d.png">

**Comment by rachael-phillips** [comment]
**Homepage**
-  the blue background image should be the same as what’s on the patternfly.org/v4 website. This is what it currently is:
<img width="1444" alt="Screen Shot 2019-10-31 at 10 52 12 AM" src="https://user-images.githubusercontent.com/40275806/67957788-8385e080-fbcc-11e9-9376-1e6e16b30a4f.png">

- Check font sizes across the homepage because many need to be updated. 
The screen shots below are places where the font should be updated: 
<img width="427" alt="Screen Shot 2019-10-31 at 10 53 08 AM" src="https://user-images.githubusercontent.com/40275806/67957890-a7e1bd00-fbcc-11e9-88fb-13f61fa10038.png">
    - Font sizes and alignment on the About PatternFly section need to be updated to be bigger to match the PF4 website
<img width="513" alt="Screen Shot 2019-10-31 at 10 54 08 AM" src="https://user-images.githubusercontent.com/40275806/67957991-ca73d600-fbcc-11e9-82b9-0b8fd7ecfa4f.png">
    - The font size needs to be bigger on the homepage under PatternFly principles
<img width="639" alt="Screen Shot 2019-10-31 at 10 54 32 AM" src="https://user-images.githubusercontent.com/40275806/67958020-d52e6b00-fbcc-11e9-8e36-62f6d2e91ec9.png">

- We need PatternFly principles to be aligned with the rest of the text and the footer

<img width="468" alt="Screen Shot 2019-10-31 at 10 55 18 AM" src="https://user-images.githubusercontent.com/40275806/67958127-03ac4600-fbcd-11e9-878f-8dc14a7e0ffb.png">


Needs to be:

<img width="362" alt="Screen Shot 2019-10-31 at 10 55 24 AM" src="https://user-images.githubusercontent.com/40275806/67958121-fee79200-fbcc-11e9-81bd-f32b4b2559d7.png">

- Search: there should be an underline on the search field
    - Styling of search field text needs to be updated. It should look like:
<img width="223" alt="Screen Shot 2019-10-31 at 10 56 07 AM" src="https://user-images.githubusercontent.com/40275806/67958156-145cbc00-fbcd-11e9-8753-c34794172912.png">


Release notes
- The code snippets on the release notes page need styling that appears on PatternFly 4 currently


All pages - headers are missing
- Some font sizes are different across the pages, so double check all font sizes. They should align with current PF4 site
- Remove props header and the bottom of the page

A11y page
- Table on accessibility page looks like it is missing structure and styling
- (Known issue) colors)

Typography page
- The header needs to be updated to remove “Design-guidelines” text and the Table of Contents

Component pages
- Remove “Design” header from components pages - this section needs to look exactly like the PatternFly 4 website

Across pages add spacing to the bottom of the page for breathing room

FRAMEWORK

Get in touch styles are not sticking 

Code needs to be made bigger

Remove dark theme on HTML components and React components

**Comment by rachael-phillips** [comment]
- Homepage

 - the blue background image should be the same as what’s on the patternfly.org/v4 website
- Check font sizes across the homepage because many need to be updated. 
    - Font sizes and alignment on the About PatternFly section need to be updated to be bigger to match the PF4 website
    - The font size needs to be bigger on the homepage under PatternFly principles
- We need PatternFly principles to be aligned with the rest of the text and the footer
- Search: there should be an underline on the search field
    - Styling of search field text needs to be updated

Release notes
- The code snippets on the release notes page need styling that appears on PatternFly 4 currently

All pages - headers are missing
- Some font sizes are different across the pages, so double check all font sizes. They should align with current PF4 site
- Remove props header and the bottom of the page

A11y page
- Table on accessibility page looks like it is missing structure and styling
- (Known issue) colors)

Typography page
- The header needs to be updated to remove “Design-guidelines” text and the Table of Contents

Component pages
- Remove “Design” header from components pages - this section needs to look exactly like the PatternFly 4 website

Across pages add spacing to the bottom of the page for breathing room

FRAMEWORK

Get in touch styles are not sticking 

Code needs to be made bigger

Remove dark theme on HTML components and React components

**Comment by rachael-phillips** [comment]
Hamburger icon should not appear until the screen is resized and responsive behavior kicks in. Right now it is non-functional: 

<img width="152" alt="Screen Shot 2019-10-31 at 1 41 14 PM" src="https://user-images.githubusercontent.com/40275806/67971948-2007ad00-fbe4-11e9-937a-74bd0a118bcd.png">

**Comment by rachael-phillips** [comment]
Hi! I wanted to capture my notes from yesterday. 

**Nav**
- Remove hamburger icon
- Responsive behavior: It should reappear once the screen is resized to a mobile view

**

**Homepage**
- The background image needs to look just like the blue background image on the homepage. Right now it does now.
<img width="1559" alt="Screen Shot 2019-11-01 at 8 57 44 AM" src="https://user-images.githubusercontent.com/40275806/68026319-c6f05580-fc85-11e9-836b-b7ffd348d198.png">

- We talked about the alignment on PatternFly principle section and the text, so I know that is underway

**Across all markdown pages**
- We are having issues with spacing across all pages and we need to have this smoothed out for release. 
- Add table styling for markdown pages as seen here:

**Comment by rachael-phillips** [comment]
Release notes page spacing need to be fixed:

<img width="732" alt="Screen Shot 2019-11-01 at 11 15 39 AM" src="https://user-images.githubusercontent.com/40275806/68034918-01172280-fc99-11e9-882d-0a9ae771e29b.png">

Global CSS needs to be fixed:

<img width="580" alt="Screen Shot 2019-11-01 at 11 20 12 AM" src="https://user-images.githubusercontent.com/40275806/68035235-9b776600-fc99-11e9-97d0-810d1f2a7d56.png">

Release notes:
<img width="894" alt="Screen Shot 2019-11-01 at 11 22 28 AM" src="https://user-images.githubusercontent.com/40275806/68035412-eee9b400-fc99-11e9-9229-4479df3e8baf.png">

**Comment by rachael-phillips** [comment]
We're still having a couple of markdown issues. Should exist on all usage and behavior pages. 

Header placement:
The space between header and content needs to be smaller as seen here:
<img width="302" alt="Screen Shot 2019-11-01 at 1 14 19 PM" src="https://user-images.githubusercontent.com/40275806/68042581-a803ba80-fca9-11e9-8ec3-b263a6b8948a.png">

This text should be formatted like this. 
<img width="315" alt="Screen Shot 2019-11-01 at 1 14 24 PM" src="https://user-images.githubusercontent.com/40275806/68042641-c49ff280-fca9-11e9-82f5-8ebbedcbccfb.png">

**Comment by rachael-phillips** [comment]
Here is where the markdown is acting a bit funky:
- Voice page:
<img width="339" alt="Screen Shot 2019-11-01 at 1 20 01 PM" src="https://user-images.githubusercontent.com/40275806/68042859-560f6480-fcaa-11e9-9ee7-7b249b4ada03.png">
Write for accessibility: 
<img width="524" alt="Screen Shot 2019-11-01 at 1 20 28 PM" src="https://user-images.githubusercontent.com/40275806/68042916-750df680-fcaa-11e9-9edc-f291579fdb00.png">

Style guide
- Punctuation section:
<img width="817" alt="Screen Shot 2019-11-01 at 1 21 45 PM" src="https://user-images.githubusercontent.com/40275806/68042998-a7b7ef00-fcaa-11e9-9bd0-389ec07c8910.png">

**Comment by mcoker** [comment]
on http://patternfly-org-preview.s3-website.us-east-2.amazonaws.com/design-guidelines/usage-and-behavior/charts, there is a sentence "Segment fill: We recommend using Colors for charts for different items within the donut chart." where "Colors" for charts links to the wrong page (404s). It should link to `/design-guidelines/styles/colors-for-charts`

**Comment by mcoker** [comment]
on http://patternfly-org-preview.s3-website.us-east-2.amazonaws.com/documentation/react/demos/bulkselecttable, the title for the example is "no title", and if you click on the external link icon at the bottom, it 404's.

**Comment by mcoker** [comment]
on http://patternfly-org-preview.s3-website.us-east-2.amazonaws.com/design-guidelines/styles/spacers, there is a link "Click here for all variables" that 404's. Should link to `/documentation/overview/global-css-variables`

**Comment by rachael-phillips** [comment]
Issues that I see on Documentation pages. This does not need to be a blocker for today, but every Props section needs a grey background to distinguish it from the rest of the page: 

![image (5)](https://user-images.githubusercontent.com/40275806/68047499-f074a580-fcb4-11e9-9a39-e1994ecbbe8c.png)

**Comment by redallen** [comment]
@rachael-phillips I added that for React when I refactored those docs. No idea it was part of the design now, lol. We can easily add it back after this release.

**Comment by redallen** [comment]
This thread has been mostly addressed. Please reopen individual issues for anything that hasn't been addressed like the Props section background!
