### ISSUE TITLE
Page component looks buggy

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/gatsby-theme-patternfly-org#82]
This example looks incorrect and needs to be updated: http://patternfly-org-staging.s3-website-us-east-1.amazonaws.com/v4/documentation/react/components/page

**Comment by redallen** [comment]
What looks buggy about it? It looks like the correctly rendered example.

If you think the example itself should be changed (i.e. made into a fullscreen example or have content/styles changed), open that issue in https://github.com/patternfly/patternfly-react . They can change the content inside that example.
