### ISSUE TITLE
Standardize H1s - H5s

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/gatsby-theme-patternfly-org#86]
During the site refactor process we discovered that the definitions of Headers were different across the site. The headers should be standardized across the site so that the _styles_ are consistent.

**Comment by redallen** [comment]
Headers have different margins whether in `pf-c-content` like in design sections, or whether rendered as `AutoLinkHeaders` from Markdown content. If we have a design as to what styles they should have (and what styles paragraphs should have) _regardless_ their context that'd do away with a few hacks like this: `const isDesignPage = ['design-guidelines', 'get-started', 'contribute'].includes(source) || navSection === 'overview';` that adds `pf-c-content` to places where we want nice `h2-6`, `ul`, `li`, `p`, and `table` spacing.

**Comment by rachael-phillips** [comment]
doc in progress: https://docs.google.com/document/d/1quYAz5CWdy29niu_FRGmSNEuUuQRHf3ch4ZFbs-mGYY/edit?usp=sharing

**Comment by redallen** [comment]
Headers are now rendered and styled consistently. If the design should change or there are specific pages with problems we can open a new issue.
