### ISSUE TITLE
Enable gzip compression

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/gatsby-theme-patternfly-org#89]
We could probably improve site load performance by enabling gzip compression. Looks like it isn't on currently

<img width="1101" alt="Screen Shot 2019-11-05 at 11 00 18 AM" src="https://user-images.githubusercontent.com/5942899/68223857-90834500-ffbb-11e9-9355-9f94cc4d4a2e.png">

**Comment by rachael-phillips** [comment]
@redallen @dlabaj  is this a viable solution for us and/or should we take this on?

**Comment by seanforyou23** [comment]
This thread seems relevant in case it helps

https://stackoverflow.com/questions/31801661/gzip-compression-on-static-amazon-s3-files

**Comment by redallen** [comment]
@seanforyou23 What's the tool you used to test the site? We're now using https://www.gatsbyjs.org/packages/gatsby-plugin-s3/ which sets the content headers in S3 to reasonable values, but I'm not sure if it gzips by default. I'd like to test it again now.

**Comment by seanforyou23** [comment]
Been using https://tools.pingdom.com/ for these types of checks for years, works pretty well and it is free!

**Comment by redallen** [comment]
There is a "Compress Objects Automatically" setting in Cloudfront that was enabled in staging but disabled in production. I've enabled it in production and now our content is gzipped.

Thanks @seanforyou23 for the catch!
