### ISSUE TITLE
Missing design guideline additions

### ISSUE THREAD

**Issue by mcarrano** [patternfly/gatsby-theme-patternfly-org#91]
Missing new design guideline documents that were added for this release. These include:

Bulk Selection: /design-guidelines/usage-and-behavior/bulk-selection

Text Input: /design-guidelines/usage-and-behavior/text-input

Pagination: /design-guidelines/usage-and-behavior/pagination

**Comment by redallen** [comment]
I think the only missing one is Pagination? These work fine:
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/text-input

**Comment by redallen** [comment]
Pagination has been added back in the caching release I just made: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/pagination

The images are rather giant, you can open another issue to downsize them.
