### ISSUE TITLE
Images on some design guideline pages not loading in Firefox

### ISSUE THREAD

**Issue by mcarrano** [patternfly/gatsby-theme-patternfly-org#92]
There are missing images on the following pages:

https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/embedded-assistance
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/navigation-system
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/progress-bar
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/wizard

All images do display when the same pages are loaded in Chrome.

**Comment by redallen** [comment]
Closed cc72510
