### ISSUE TITLE
Some design guideline pages fail to load in Firefox

### ISSUE THREAD

**Issue by mcarrano** [patternfly/gatsby-theme-patternfly-org#93]
Some pages in the design guidelines section fail to load when viewed in Firefox. These include:

https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/about-modal
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login
https://www.patternfly.org/v4/design-guidelines/content/writing
https://www.patternfly.org/v4/design-guidelines/content/voice-and-tone
https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology

All pages can be viewed in Chrome.

**Comment by redallen** [comment]
Closed by cc72510
