### ISSUE TITLE
Cannot navigate to component pages

### ISSUE THREAD

**Issue by mcarrano** [patternfly/gatsby-theme-patternfly-org#94]
In both Core and React documentation sections, I am getting inconsistent behavior when I click on navigation links in the left nav to move between component pages. In some cases the page will load and then no longer load when I return to it. Behavior differs slightly between Firefox and Chrome. Firefox will bring me to a blank page. In Chrome, clicking on the navigation link will have no effect.

**Comment by redallen** [comment]
Closed in cc72510
